export const PARKING_HISTORY_REPOSITORY_TOKEN = Symbol.for(
  "PARKING_HISTORY_REPOSITORY_TOKEN"
);

export const CALCULATE_PARKING_PRICE_STRATEGY_TOKEN = Symbol.for(
  "CALCULATE_PARKING_PRICE_STRATEGY_TOKEN"
);

export const PRICING_STRATEGY_FACTORY_TOKEN = "PRICING_STRATEGY_FACTORY_TOKEN";
